apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
spec:
  type: ClusterIP
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: dataquality
    department: data
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080